// Generated by CoffeeScript 1.7.1
var merge, misc;

merge = require('mecano/lib/misc').merge;

misc = module.exports = {
  flatten: function(arr, ret) {
    var i, _i, _ref;
    if (ret == null) {
      ret = [];
    }
    for (i = _i = 0, _ref = arr.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (Array.isArray(arr[i])) {
        misc.flatten(arr[i], ret);
      } else {
        ret.push(arr[i]);
      }
    }
    return ret;
  },
  merge: merge
};
